//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popup
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public bool Show { get; set; }
        public byte Timeout { get; set; }
    }
}
