//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_IT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.ReportPosts = new HashSet<ReportPost>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int PostID { get; set; }
        public string CategoryID { get; set; }
        public string SubCategoryID { get; set; }
        public string Title { get; set; }
        public string Introduce { get; set; }
        public string Body { get; set; }
        public string Image { get; set; }
        public string Alias { get; set; }
        public int Views { get; set; }
        public string UserID { get; set; }
        public System.DateTime DatePost { get; set; }
        public bool Show { get; set; }
        public string ImageOpenGraph { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportPost> ReportPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
